-- ===========================================================================
-- BridgeTalk — demo seed data
--
-- Run AFTER schema.sql:
--     mysql -u root -p < database/seed.sql
--
-- Purpose: the review demo must not depend on live registration working. If
-- the network, the browser or your nerves misbehave on the day, these two
-- accounts already exist and you can log straight in.
--
-- Idempotent: INSERT IGNORE means re-running this never duplicates a user and
-- never overwrites a password you have since changed.
-- ===========================================================================

USE bridgetalk;

-- ---------------------------------------------------------------------------
-- Two demo accounts, one per role
-- ---------------------------------------------------------------------------
-- Both passwords are:  bridgetalk123
--
-- These are bcrypt hashes with cost factor 12, generated by
-- backend/app/core/security.py::hash_password. They are NOT a secret being
-- leaked: the plaintext is published one line above, on purpose, because these
-- are throwaway demo accounts on a local database.
--
-- The two hashes differ even though both encode the same password. That is
-- bcrypt's per-password salt at work, and it is exactly why a leaked user
-- table cannot be cracked with one precomputed rainbow table.
--
-- The domain is example.com because RFC 2606 reserves it for documentation.
-- Using a made-up domain, or a special-use suffix like .local, gets rejected
-- by the API's email validation.
INSERT IGNORE INTO users (id, name, email, password_hash, role, created_at) VALUES
  (101,
   'Demo Deaf User',
   'deaf.demo@example.com',
   '$2b$12$6TVBFguUXul0qIwNtq.Mc.SJw723QEludzZ7/uoTkVE36abp0j/Bq',
   'deaf',
   NOW()),
  (102,
   'Demo Hearing User',
   'hearing.demo@example.com',
   '$2b$12$J6qXyoLlA.zJKTZDecGx7u79UeXXgPwgjnIVcxGFqp4xyuDrtKg2e',
   'hearing',
   NOW());

-- Explicit ids in the 100+ range keep seeded rows clearly distinguishable from
-- accounts registered through the API, which start at 1. Handy when you are
-- looking at the users table during a review and need to say which is which.

-- ---------------------------------------------------------------------------
-- A pre-created meeting to demo joining without creating one first
-- ---------------------------------------------------------------------------
-- started_at and ended_at are both NULL: the meeting exists but has not begun,
-- which is exactly the state a real "created, not yet joined" meeting is in.
INSERT IGNORE INTO meetings (id, code, title, host_id, is_interview_mode, started_at, ended_at, created_at)
VALUES
  (101, 'DEMO-01', 'BridgeTalk Review Demo', 101, FALSE, NULL, NULL, NOW());

-- ---------------------------------------------------------------------------
-- Verify
-- ---------------------------------------------------------------------------
SELECT id, name, email, role FROM users WHERE id >= 100;
SELECT id, code, title, host_id FROM meetings WHERE id >= 100;
