-- ============================================================================
-- Migration 002 — one transcript row per utterance
--
--     mysql -u bridgetalk -p bridgetalk < database/migrations/002_caption_segments.sql
--
-- Additive and idempotent. Existing rows keep a NULL segment_id and are left
-- untouched; they are the old duplicated data and deleting them is the user's
-- call, not a migration's.
--
-- THE BUG THIS FIXES
-- ------------------
-- Captions were broadcast carrying the whole ACCUMULATED sentence, and one row
-- was written per emitted word. A three-word utterance therefore produced
-- three rows reading "a", "a b", "a b c". The transcript was the same sentence
-- repeated with one more word each time.
--
-- segment_id is generated by the producer and is stable for one utterance, so
-- a UNIQUE constraint on (meeting_id, segment_id) makes a duplicate write
-- impossible at the database level rather than only by convention.
-- ============================================================================

SET @exists := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'transcripts'
    AND COLUMN_NAME = 'segment_id'
);
SET @sql := IF(@exists = 0,
  'ALTER TABLE transcripts ADD COLUMN segment_id VARCHAR(64) NULL AFTER user_id',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- UNIQUE, not just an index. A retry, a double-click or a reconnect that
-- replays the final event must not be able to create a second row. NULLs are
-- exempt from UNIQUE in MySQL, so the pre-existing rows do not collide.
SET @exists := (
  SELECT COUNT(*) FROM information_schema.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'transcripts'
    AND INDEX_NAME = 'uq_transcript_segment'
);
SET @sql := IF(@exists = 0,
  'CREATE UNIQUE INDEX uq_transcript_segment ON transcripts (meeting_id, segment_id)',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT 'migration 002 applied' AS result;
